version: "3.1"

name: "ns-canteen-menu"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ".env"
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    profiles:
      - "dev"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}

volumes:
  data:
